name: Test project
on: [push, workflow_dispatch]
jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Format code with black
        run: |
          black . --exclude="venv/*"
      - name: Sort imports with isort
        run: |
          pip install isort
          isort .
      - name: Remove unused imports with autoflake
        run: |
          pip install autoflake
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Format code with black"
          add: "."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Test application
        run: pytest
